apiVersion: v1
kind: PersistentVolume
metadata:
  name: myebsvolume2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: vol-0a6fb01d98444651e 
    fsType: ext4