apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myebsvol-pv-claim2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-storage    
  resources:
    requests:
      storage: 1Gi